import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1776072223807 implements MigrationInterface {
    name = 'InitSchema1776072223807'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" smallint PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(50) NOT NULL, "name" varchar(100) NOT NULL, CONSTRAINT "UQ_f6d54f95c31b73fb1bdd8e91d0c" UNIQUE ("code"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, "role_id" smallint, CONSTRAINT "uq_user_roles_user_role" UNIQUE ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" varchar PRIMARY KEY NOT NULL, "email_notification" boolean NOT NULL DEFAULT (1), "push_notification" boolean NOT NULL DEFAULT (0), "claim_status_notification" boolean NOT NULL DEFAULT (1), "approval_decision_notification" boolean NOT NULL DEFAULT (1), "weekly_summary" boolean NOT NULL DEFAULT (1), "theme" varchar(20) NOT NULL DEFAULT ('light'), "language" varchar(10) NOT NULL DEFAULT ('en'), "default_page" varchar(30) NOT NULL DEFAULT ('dashboard'), "rows_per_page" integer NOT NULL DEFAULT (25), "remember_session" boolean NOT NULL DEFAULT (1), "two_factor_auth" boolean NOT NULL DEFAULT (0), "login_alert" boolean NOT NULL DEFAULT (1), "auto_logout" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "REL_4ed056b9344e6f7d8d46ec4b30" UNIQUE ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "full_name" varchar(150) NOT NULL, "email" varchar(255) NOT NULL, "password_hash" text NOT NULL, "phone_number" varchar(20), "nik" varchar(30), "birth_place" varchar(100), "birth_date" date, "address" text, "city" varchar(100), "province" varchar(100), "postal_code" varchar(10), "email_verified_at" datetime, "is_active" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_e57d66dc56e6d164b6467776bb7" UNIQUE ("nik"))`);
        await queryRunner.query(`CREATE TABLE "user_tokens" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar(50) NOT NULL, "token" text NOT NULL, "is_used" boolean NOT NULL DEFAULT (0), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "UQ_4e993847043f5bf10656b917985" UNIQUE ("token"))`);
        await queryRunner.query(`CREATE TABLE "claim_statuses" ("id" smallint PRIMARY KEY AUTOINCREMENT NOT NULL, "code" varchar(50) NOT NULL, "name" varchar(100) NOT NULL, "sequence" smallint NOT NULL, CONSTRAINT "UQ_0d4f122404994f148a315dbd3ce" UNIQUE ("code"))`);
        await queryRunner.query(`CREATE TABLE "claim_status_histories" ("id" varchar PRIMARY KEY NOT NULL, "action_role" varchar(50) NOT NULL, "note" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "from_status_id" smallint, "to_status_id" smallint NOT NULL, "action_by" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "claim_attachments" ("id" varchar PRIMARY KEY NOT NULL, "original_file_name" varchar(255) NOT NULL, "stored_file_name" varchar(255) NOT NULL, "file_url" text NOT NULL, "file_extension" varchar(20) NOT NULL, "file_mime_type" varchar(100) NOT NULL, "file_size" bigint NOT NULL, "storage_disk" varchar(50) NOT NULL DEFAULT ('local'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "uploaded_by" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "claim_comments" ("id" varchar PRIMARY KEY NOT NULL, "comment_type" varchar(30) NOT NULL, "comment_text" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "created_by" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "claims" ("id" varchar PRIMARY KEY NOT NULL, "claim_number" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "description" text, "claim_amount" numeric(18,2) NOT NULL, "incident_date" date NOT NULL, "submitted_at" datetime, "reviewed_at" datetime, "decided_at" datetime, "rejection_reason" text, "version" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "user_id" varchar NOT NULL, "current_status_id" smallint NOT NULL, "reviewed_by" varchar, "decided_by" varchar)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_383f456e8c7dda0114c49d47c5" ON "claims" ("claim_number") `);
        await queryRunner.query(`CREATE TABLE "idempotency_keys" ("id" varchar PRIMARY KEY NOT NULL, "key" varchar(255) NOT NULL, "resource_type" varchar(100) NOT NULL, "resource_id" varchar, "request_hash" text NOT NULL, "response_code" integer, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "expired_at" datetime NOT NULL, "actor_id" varchar NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0afd83cbf08c9d12089a9bffc5" ON "idempotency_keys" ("key") `);
        await queryRunner.query(`CREATE TABLE "temporary_user_roles" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, "role_id" smallint, CONSTRAINT "uq_user_roles_user_role" UNIQUE ("user_id", "role_id"), CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user_roles"("id", "created_at", "user_id", "role_id") SELECT "id", "created_at", "user_id", "role_id" FROM "user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_roles" RENAME TO "user_roles"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_settings" ("id" varchar PRIMARY KEY NOT NULL, "email_notification" boolean NOT NULL DEFAULT (1), "push_notification" boolean NOT NULL DEFAULT (0), "claim_status_notification" boolean NOT NULL DEFAULT (1), "approval_decision_notification" boolean NOT NULL DEFAULT (1), "weekly_summary" boolean NOT NULL DEFAULT (1), "theme" varchar(20) NOT NULL DEFAULT ('light'), "language" varchar(10) NOT NULL DEFAULT ('en'), "default_page" varchar(30) NOT NULL DEFAULT ('dashboard'), "rows_per_page" integer NOT NULL DEFAULT (25), "remember_session" boolean NOT NULL DEFAULT (1), "two_factor_auth" boolean NOT NULL DEFAULT (0), "login_alert" boolean NOT NULL DEFAULT (1), "auto_logout" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "REL_4ed056b9344e6f7d8d46ec4b30" UNIQUE ("user_id"), CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user_settings"("id", "email_notification", "push_notification", "claim_status_notification", "approval_decision_notification", "weekly_summary", "theme", "language", "default_page", "rows_per_page", "remember_session", "two_factor_auth", "login_alert", "auto_logout", "created_at", "updated_at", "user_id") SELECT "id", "email_notification", "push_notification", "claim_status_notification", "approval_decision_notification", "weekly_summary", "theme", "language", "default_page", "rows_per_page", "remember_session", "two_factor_auth", "login_alert", "auto_logout", "created_at", "updated_at", "user_id" FROM "user_settings"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_settings" RENAME TO "user_settings"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_tokens" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar(50) NOT NULL, "token" text NOT NULL, "is_used" boolean NOT NULL DEFAULT (0), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "UQ_4e993847043f5bf10656b917985" UNIQUE ("token"), CONSTRAINT "FK_9e144a67be49e5bba91195ef5de" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_user_tokens"("id", "type", "token", "is_used", "expires_at", "created_at", "user_id") SELECT "id", "type", "token", "is_used", "expires_at", "created_at", "user_id" FROM "user_tokens"`);
        await queryRunner.query(`DROP TABLE "user_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_tokens" RENAME TO "user_tokens"`);
        await queryRunner.query(`CREATE TABLE "temporary_claim_status_histories" ("id" varchar PRIMARY KEY NOT NULL, "action_role" varchar(50) NOT NULL, "note" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "from_status_id" smallint, "to_status_id" smallint NOT NULL, "action_by" varchar NOT NULL, CONSTRAINT "FK_3d02024277029d8473fe1ad5acc" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_fb5a69b0e531dcf3041f01b5f97" FOREIGN KEY ("from_status_id") REFERENCES "claim_statuses" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_eaa7b2f731c09c8ce5fcaca7851" FOREIGN KEY ("to_status_id") REFERENCES "claim_statuses" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_2eb98659870b0bdf90dfe578fdf" FOREIGN KEY ("action_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_claim_status_histories"("id", "action_role", "note", "created_at", "claim_id", "from_status_id", "to_status_id", "action_by") SELECT "id", "action_role", "note", "created_at", "claim_id", "from_status_id", "to_status_id", "action_by" FROM "claim_status_histories"`);
        await queryRunner.query(`DROP TABLE "claim_status_histories"`);
        await queryRunner.query(`ALTER TABLE "temporary_claim_status_histories" RENAME TO "claim_status_histories"`);
        await queryRunner.query(`CREATE TABLE "temporary_claim_attachments" ("id" varchar PRIMARY KEY NOT NULL, "original_file_name" varchar(255) NOT NULL, "stored_file_name" varchar(255) NOT NULL, "file_url" text NOT NULL, "file_extension" varchar(20) NOT NULL, "file_mime_type" varchar(100) NOT NULL, "file_size" bigint NOT NULL, "storage_disk" varchar(50) NOT NULL DEFAULT ('local'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "uploaded_by" varchar NOT NULL, CONSTRAINT "FK_72bc6efcd1422bc7c4200192f2b" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_725e9d29873a9109a3f08d76650" FOREIGN KEY ("uploaded_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_claim_attachments"("id", "original_file_name", "stored_file_name", "file_url", "file_extension", "file_mime_type", "file_size", "storage_disk", "created_at", "claim_id", "uploaded_by") SELECT "id", "original_file_name", "stored_file_name", "file_url", "file_extension", "file_mime_type", "file_size", "storage_disk", "created_at", "claim_id", "uploaded_by" FROM "claim_attachments"`);
        await queryRunner.query(`DROP TABLE "claim_attachments"`);
        await queryRunner.query(`ALTER TABLE "temporary_claim_attachments" RENAME TO "claim_attachments"`);
        await queryRunner.query(`CREATE TABLE "temporary_claim_comments" ("id" varchar PRIMARY KEY NOT NULL, "comment_type" varchar(30) NOT NULL, "comment_text" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "created_by" varchar NOT NULL, CONSTRAINT "FK_635fdea1aee993016389f7713ad" FOREIGN KEY ("claim_id") REFERENCES "claims" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_170f13a3e6471b47f1cb6327374" FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_claim_comments"("id", "comment_type", "comment_text", "created_at", "claim_id", "created_by") SELECT "id", "comment_type", "comment_text", "created_at", "claim_id", "created_by" FROM "claim_comments"`);
        await queryRunner.query(`DROP TABLE "claim_comments"`);
        await queryRunner.query(`ALTER TABLE "temporary_claim_comments" RENAME TO "claim_comments"`);
        await queryRunner.query(`DROP INDEX "IDX_383f456e8c7dda0114c49d47c5"`);
        await queryRunner.query(`CREATE TABLE "temporary_claims" ("id" varchar PRIMARY KEY NOT NULL, "claim_number" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "description" text, "claim_amount" numeric(18,2) NOT NULL, "incident_date" date NOT NULL, "submitted_at" datetime, "reviewed_at" datetime, "decided_at" datetime, "rejection_reason" text, "version" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "user_id" varchar NOT NULL, "current_status_id" smallint NOT NULL, "reviewed_by" varchar, "decided_by" varchar, CONSTRAINT "FK_6b6d7ad7d8c3982b44194fd542c" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_232e9b9399df201bb5ed7fb8963" FOREIGN KEY ("current_status_id") REFERENCES "claim_statuses" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_6c5e93ffaf645b7d0e6b439876b" FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION, CONSTRAINT "FK_82c46bddd60b97d26e32019eaab" FOREIGN KEY ("decided_by") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_claims"("id", "claim_number", "title", "description", "claim_amount", "incident_date", "submitted_at", "reviewed_at", "decided_at", "rejection_reason", "version", "created_at", "updated_at", "deleted_at", "user_id", "current_status_id", "reviewed_by", "decided_by") SELECT "id", "claim_number", "title", "description", "claim_amount", "incident_date", "submitted_at", "reviewed_at", "decided_at", "rejection_reason", "version", "created_at", "updated_at", "deleted_at", "user_id", "current_status_id", "reviewed_by", "decided_by" FROM "claims"`);
        await queryRunner.query(`DROP TABLE "claims"`);
        await queryRunner.query(`ALTER TABLE "temporary_claims" RENAME TO "claims"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_383f456e8c7dda0114c49d47c5" ON "claims" ("claim_number") `);
        await queryRunner.query(`DROP INDEX "IDX_0afd83cbf08c9d12089a9bffc5"`);
        await queryRunner.query(`CREATE TABLE "temporary_idempotency_keys" ("id" varchar PRIMARY KEY NOT NULL, "key" varchar(255) NOT NULL, "resource_type" varchar(100) NOT NULL, "resource_id" varchar, "request_hash" text NOT NULL, "response_code" integer, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "expired_at" datetime NOT NULL, "actor_id" varchar NOT NULL, CONSTRAINT "FK_a2af91410963bee3a8e0146d194" FOREIGN KEY ("actor_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_idempotency_keys"("id", "key", "resource_type", "resource_id", "request_hash", "response_code", "created_at", "expired_at", "actor_id") SELECT "id", "key", "resource_type", "resource_id", "request_hash", "response_code", "created_at", "expired_at", "actor_id" FROM "idempotency_keys"`);
        await queryRunner.query(`DROP TABLE "idempotency_keys"`);
        await queryRunner.query(`ALTER TABLE "temporary_idempotency_keys" RENAME TO "idempotency_keys"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0afd83cbf08c9d12089a9bffc5" ON "idempotency_keys" ("key") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "IDX_0afd83cbf08c9d12089a9bffc5"`);
        await queryRunner.query(`ALTER TABLE "idempotency_keys" RENAME TO "temporary_idempotency_keys"`);
        await queryRunner.query(`CREATE TABLE "idempotency_keys" ("id" varchar PRIMARY KEY NOT NULL, "key" varchar(255) NOT NULL, "resource_type" varchar(100) NOT NULL, "resource_id" varchar, "request_hash" text NOT NULL, "response_code" integer, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "expired_at" datetime NOT NULL, "actor_id" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "idempotency_keys"("id", "key", "resource_type", "resource_id", "request_hash", "response_code", "created_at", "expired_at", "actor_id") SELECT "id", "key", "resource_type", "resource_id", "request_hash", "response_code", "created_at", "expired_at", "actor_id" FROM "temporary_idempotency_keys"`);
        await queryRunner.query(`DROP TABLE "temporary_idempotency_keys"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0afd83cbf08c9d12089a9bffc5" ON "idempotency_keys" ("key") `);
        await queryRunner.query(`DROP INDEX "IDX_383f456e8c7dda0114c49d47c5"`);
        await queryRunner.query(`ALTER TABLE "claims" RENAME TO "temporary_claims"`);
        await queryRunner.query(`CREATE TABLE "claims" ("id" varchar PRIMARY KEY NOT NULL, "claim_number" varchar(50) NOT NULL, "title" varchar(200) NOT NULL, "description" text, "claim_amount" numeric(18,2) NOT NULL, "incident_date" date NOT NULL, "submitted_at" datetime, "reviewed_at" datetime, "decided_at" datetime, "rejection_reason" text, "version" integer NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "deleted_at" datetime, "user_id" varchar NOT NULL, "current_status_id" smallint NOT NULL, "reviewed_by" varchar, "decided_by" varchar)`);
        await queryRunner.query(`INSERT INTO "claims"("id", "claim_number", "title", "description", "claim_amount", "incident_date", "submitted_at", "reviewed_at", "decided_at", "rejection_reason", "version", "created_at", "updated_at", "deleted_at", "user_id", "current_status_id", "reviewed_by", "decided_by") SELECT "id", "claim_number", "title", "description", "claim_amount", "incident_date", "submitted_at", "reviewed_at", "decided_at", "rejection_reason", "version", "created_at", "updated_at", "deleted_at", "user_id", "current_status_id", "reviewed_by", "decided_by" FROM "temporary_claims"`);
        await queryRunner.query(`DROP TABLE "temporary_claims"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_383f456e8c7dda0114c49d47c5" ON "claims" ("claim_number") `);
        await queryRunner.query(`ALTER TABLE "claim_comments" RENAME TO "temporary_claim_comments"`);
        await queryRunner.query(`CREATE TABLE "claim_comments" ("id" varchar PRIMARY KEY NOT NULL, "comment_type" varchar(30) NOT NULL, "comment_text" text NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "created_by" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "claim_comments"("id", "comment_type", "comment_text", "created_at", "claim_id", "created_by") SELECT "id", "comment_type", "comment_text", "created_at", "claim_id", "created_by" FROM "temporary_claim_comments"`);
        await queryRunner.query(`DROP TABLE "temporary_claim_comments"`);
        await queryRunner.query(`ALTER TABLE "claim_attachments" RENAME TO "temporary_claim_attachments"`);
        await queryRunner.query(`CREATE TABLE "claim_attachments" ("id" varchar PRIMARY KEY NOT NULL, "original_file_name" varchar(255) NOT NULL, "stored_file_name" varchar(255) NOT NULL, "file_url" text NOT NULL, "file_extension" varchar(20) NOT NULL, "file_mime_type" varchar(100) NOT NULL, "file_size" bigint NOT NULL, "storage_disk" varchar(50) NOT NULL DEFAULT ('local'), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "uploaded_by" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "claim_attachments"("id", "original_file_name", "stored_file_name", "file_url", "file_extension", "file_mime_type", "file_size", "storage_disk", "created_at", "claim_id", "uploaded_by") SELECT "id", "original_file_name", "stored_file_name", "file_url", "file_extension", "file_mime_type", "file_size", "storage_disk", "created_at", "claim_id", "uploaded_by" FROM "temporary_claim_attachments"`);
        await queryRunner.query(`DROP TABLE "temporary_claim_attachments"`);
        await queryRunner.query(`ALTER TABLE "claim_status_histories" RENAME TO "temporary_claim_status_histories"`);
        await queryRunner.query(`CREATE TABLE "claim_status_histories" ("id" varchar PRIMARY KEY NOT NULL, "action_role" varchar(50) NOT NULL, "note" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "claim_id" varchar, "from_status_id" smallint, "to_status_id" smallint NOT NULL, "action_by" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "claim_status_histories"("id", "action_role", "note", "created_at", "claim_id", "from_status_id", "to_status_id", "action_by") SELECT "id", "action_role", "note", "created_at", "claim_id", "from_status_id", "to_status_id", "action_by" FROM "temporary_claim_status_histories"`);
        await queryRunner.query(`DROP TABLE "temporary_claim_status_histories"`);
        await queryRunner.query(`ALTER TABLE "user_tokens" RENAME TO "temporary_user_tokens"`);
        await queryRunner.query(`CREATE TABLE "user_tokens" ("id" varchar PRIMARY KEY NOT NULL, "type" varchar(50) NOT NULL, "token" text NOT NULL, "is_used" boolean NOT NULL DEFAULT (0), "expires_at" datetime NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "UQ_4e993847043f5bf10656b917985" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "user_tokens"("id", "type", "token", "is_used", "expires_at", "created_at", "user_id") SELECT "id", "type", "token", "is_used", "expires_at", "created_at", "user_id" FROM "temporary_user_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_user_tokens"`);
        await queryRunner.query(`ALTER TABLE "user_settings" RENAME TO "temporary_user_settings"`);
        await queryRunner.query(`CREATE TABLE "user_settings" ("id" varchar PRIMARY KEY NOT NULL, "email_notification" boolean NOT NULL DEFAULT (1), "push_notification" boolean NOT NULL DEFAULT (0), "claim_status_notification" boolean NOT NULL DEFAULT (1), "approval_decision_notification" boolean NOT NULL DEFAULT (1), "weekly_summary" boolean NOT NULL DEFAULT (1), "theme" varchar(20) NOT NULL DEFAULT ('light'), "language" varchar(10) NOT NULL DEFAULT ('en'), "default_page" varchar(30) NOT NULL DEFAULT ('dashboard'), "rows_per_page" integer NOT NULL DEFAULT (25), "remember_session" boolean NOT NULL DEFAULT (1), "two_factor_auth" boolean NOT NULL DEFAULT (0), "login_alert" boolean NOT NULL DEFAULT (1), "auto_logout" boolean NOT NULL DEFAULT (1), "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, CONSTRAINT "REL_4ed056b9344e6f7d8d46ec4b30" UNIQUE ("user_id"))`);
        await queryRunner.query(`INSERT INTO "user_settings"("id", "email_notification", "push_notification", "claim_status_notification", "approval_decision_notification", "weekly_summary", "theme", "language", "default_page", "rows_per_page", "remember_session", "two_factor_auth", "login_alert", "auto_logout", "created_at", "updated_at", "user_id") SELECT "id", "email_notification", "push_notification", "claim_status_notification", "approval_decision_notification", "weekly_summary", "theme", "language", "default_page", "rows_per_page", "remember_session", "two_factor_auth", "login_alert", "auto_logout", "created_at", "updated_at", "user_id" FROM "temporary_user_settings"`);
        await queryRunner.query(`DROP TABLE "temporary_user_settings"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME TO "temporary_user_roles"`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("id" varchar PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "user_id" varchar, "role_id" smallint, CONSTRAINT "uq_user_roles_user_role" UNIQUE ("user_id", "role_id"))`);
        await queryRunner.query(`INSERT INTO "user_roles"("id", "created_at", "user_id", "role_id") SELECT "id", "created_at", "user_id", "role_id" FROM "temporary_user_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_user_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_0afd83cbf08c9d12089a9bffc5"`);
        await queryRunner.query(`DROP TABLE "idempotency_keys"`);
        await queryRunner.query(`DROP INDEX "IDX_383f456e8c7dda0114c49d47c5"`);
        await queryRunner.query(`DROP TABLE "claims"`);
        await queryRunner.query(`DROP TABLE "claim_comments"`);
        await queryRunner.query(`DROP TABLE "claim_attachments"`);
        await queryRunner.query(`DROP TABLE "claim_status_histories"`);
        await queryRunner.query(`DROP TABLE "claim_statuses"`);
        await queryRunner.query(`DROP TABLE "user_tokens"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "user_settings"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
